// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
  API: {
      GraphQL: {
        endpoint: 'https://mtbla22ahfevfl4sdtipq776tm.appsync-api.sa-east-1.amazonaws.com/graphql',
        region: 'sa-east-1',
        defaultAuthMode: 'iam',
      }
  }
};

export default config;